Traceback (most recent call last):
  File "/home/runner/micromamba-root/envs/buildenv/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/runner/micromamba-root/envs/buildenv/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/micromamba-root/envs/buildenv/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/runner/micromamba-root/envs/buildenv/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/runner/micromamba-root/envs/buildenv/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/runner/micromamba-root/envs/buildenv/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/runner/micromamba-root/envs/buildenv/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/micromamba-root/envs/buildenv/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from ocpmodels.preprocessing import AtomsToGraphs
from ocpmodels.datasets import SinglePointLmdbDataset, TrajectoryLmdbDataset
import ase.io
from ase.build import bulk
from ase.build import fcc100, add_adsorbate, molecule
from ase.constraints import FixAtoms
from ase.calculators.emt import EMT
from ase.optimize import BFGS
import matplotlib.pyplot as plt
import lmdb
import pickle
from tqdm import tqdm
import torch
import os
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn [1], line 1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mocpmodels[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpreprocessing[39;00m [38;5;28;01mimport[39;00m AtomsToGraphs
[1;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mocpmodels[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdatasets[39;00m [38;5;28;01mimport[39;00m SinglePointLmdbDataset, TrajectoryLmdbDataset
[1;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mase[39;00m[38;5;21;01m.[39;00m[38;5;21;01mio[39;00m

File [0;32m~/work/ml_catalysis_tutorials/ml_catalysis_tutorials/ocp/ocpmodels/preprocessing/__init__.py:8[0m
[1;32m      1[0m [38;5;124;03m"""[39;00m
[1;32m      2[0m [38;5;124;03mCopyright (c) Facebook, Inc. and its affiliates.[39;00m
[1;32m      3[0m 
[1;32m      4[0m [38;5;124;03mThis source code is licensed under the MIT license found in the[39;00m
[1;32m      5[0m [38;5;124;03mLICENSE file in the root directory of this source tree.[39;00m
[1;32m      6[0m [38;5;124;03m"""[39;00m
[0;32m----> 8[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01matoms_to_graphs[39;00m [38;5;28;01mimport[39;00m AtomsToGraphs

File [0;32m~/work/ml_catalysis_tutorials/ml_catalysis_tutorials/ocp/ocpmodels/preprocessing/atoms_to_graphs.py:8[0m
[1;32m      1[0m [38;5;124;03m"""[39;00m
[1;32m      2[0m [38;5;124;03mCopyright (c) Facebook, Inc. and its affiliates.[39;00m
[1;32m      3[0m 
[1;32m      4[0m [38;5;124;03mThis source code is licensed under the MIT license found in the[39;00m
[1;32m      5[0m [38;5;124;03mLICENSE file in the root directory of this source tree.[39;00m
[1;32m      6[0m [38;5;124;03m"""[39;00m
[0;32m----> 8[0m [38;5;28;01mimport[39;00m [38;5;21;01mase[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdb[39;00m[38;5;21;01m.[39;00m[38;5;21;01msqlite[39;00m
[1;32m      9[0m [38;5;28;01mimport[39;00m [38;5;21;01mase[39;00m[38;5;21;01m.[39;00m[38;5;21;01mio[39;00m[38;5;21;01m.[39;00m[38;5;21;01mtrajectory[39;00m
[1;32m     10[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m

[0;31mModuleNotFoundError[0m: No module named 'ase'
ModuleNotFoundError: No module named 'ase'

